package com.nhnacademy.domain.Header;

public enum MessageType {
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    LOGOUT,
    LOGOUT_SUCCESS,
    CREATE_ROOM,
    CREATE_ROOM_SUCCESS,
    ROOM_LIST,
    ROOM_LIST_RESPONSE,
    JOIN_ROOM,
    JOIN_ROOM_SUCCESS,
    JOIN_ROOM_FAIL,
    ROOM_USER_LIST,
    ROOM_USER_LIST_RESPONSE,
    CHAT_MESSAGE,
    CHAT_MESSAGE_SUCCESS,
    WHISPER_MESSAGE,
    WHISPER_MESSAGE_SUCCESS,
    WHISPER_MESSAGE_RECEIVE,
    MESSAGE_HISTORY,
    MESSAGE_HISTORY_RESPONSE,
    LEAVE_ROOM,
    LEAVE_ROOM_SUCCESS,
    ERROR
}
